version: '3.3'

services:
  sdk:
    image: 'cpsxblock/sdkenv'
    container_name: xblock-coconstruct-sdkenv
    build: 
      context: ./
      dockerfile: ./docker/sdk/Dockerfile
  app:
    container_name: xblock-coconstruct-app
    build: 
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '5000:8000'
    volumes:
      - './constructcpsxblock/constructcpsxblock/static:/usr/local/var/xblock/constructcpsxblock/constructcpsxblock/static'
